### PR TITLE
Automatically add to user-startup.sh to persist across Linux updates

### PR DESCRIPTION
**Pull request by c0d3h4x0r**

### CODE REVIEW

**Comment by sorgelig** [comment]
I don't think it's a good idea to ramp-up to such insane speed. Especially UART port in Cyclone V is buggy and DMA is off, higher UART speed will load CPU even more.
It doesn't impact work in normal cores. Only Main cores has excessive debug output.

**Comment by c0d3h4x0r** [comment]
Without this, anytime a running core switches its video resolution -- even if the HDMI video mode isn't changing at all -- MiSTer totally drops all inputs from all devices (keyboard, mouse, gamepad, etc) for a duration long enough to interfere with gameplay.  I have two identical MiSTers made entirely of official boards from Ricardo and MisterAddons, and they both have the same problem, so it is not defective hardware.

All cores cause the `MiSTer` process to emit a bunch of log output to the Linux console while they run.  Because the console is redirected to the serial port, if too much log output happens too fast (like during video resolution changes), it blocks the `MiSTer` process and slows it down.

What I _really_ need is a way to completely disable the redirection of all console output to the serial port.  But I tried using `console=null` in `u-boot.txt`, and it doesn't work.  I think because `console=ttyS0` is already set in the ARM build of the kernel, it rejects/ignores the additional `console=null` parameter (per the Linux kernel documentation).

Can you instead suggest or provide a way for me to disable redirection of console to the serial port?

**Comment by sorgelig** [comment]
It seems you use completely different MiSTer. Probably something heavily modded in software. In my MiSTer HDMI resolution getting set on start of the core and doesn't change. So there is no affection you describing. Also changing HDMI is quite stressful action for MiSTer as many things inside need to be changed.
For redirection: you may start Main with stdout and stderr redirected to null. For example, if you connect over SSH and then restart MiSTer process from SSH, then all output will go to SSH console. So similarly can be started with MiSTer 1>/dev/null 2>/dev/null (or similar, i forgot the proper syntax).

**Comment by c0d3h4x0r** [comment]
I'm not talking about HDMI resolution changes. Note I said "even if the HDMI video mode isn't changing at all".

I'm talking about the running core's internal resolution changes. Many cores do this while running, such as Minimig, ao486, and even consoles such as Genesis. One good example is the Genesis game "Sonic the Hedgehog 2", which changes to 448i for 2-player splitscreen mode but uses 224p for everything else.  Another good example is the Amiga game "Agony", which switches between high resolution loading screens and low resolution levels. Even if the HDMI video mode does not change (using `vscale_mode=1`), the running core does change its internal/original resolution during gameplay, which causes the `MiSTer` process to writr a bunch of log output to the Linux console, which is redirected to the slow serial port, which makes the `MiSTer` process briefly hang/stall while logging, during which it ignores all inputs.

This is not a hardware problem. It is a software problem caused by redirecting all console output to the serial port.  If I redirect all `MiSTer` process output to `/dev/null` or boost the serial port baud rate to 4000000, then the problem goes away.

But redirecting all `MiSTer` process output to `/dev/null` requires hand-modifying `/etc/inittab`, which will get undone every time there's a Linux update. And it also doesn't stop ALL logging to serial port -- it only stops logging from the `MiSTer` process.  Other logging -- such as from the Linux kernel -- still goes to serial port, which will still impact overall system performance.

Logging to serial port should not be the default, because most users will never use it and it hurts system performance. Default should be logging to null, and then the minority of users who want to debug over serial can opt-in by adding `console=ttyS0` to their `u-boot.txt`.

**Comment by sorgelig** [comment]
I don't notice such big problems as you describe. Even games you mentioned i know well. They switch resolution not during game play so there is no affection from resolution changes. In 6 years of MiSTer there was no report of such problem. If i would notice it, i would change it long time age already.

Disabling console by default doesn't look good as it will require more preparations to get the log, and it will require reboot. Sometimes users need to provide such logs.

**Comment by c0d3h4x0r** [comment]
This is a big problem for many games.  Input gets dropped for anywhere from 0.5-4 seconds, depending upon the size of the user's INI file, because the INI file gets reparsed twice on every core resolution change, and each parsing pass dumps a lot of log output lines in very short time.  I have to use a large INI file with lots of `[video=...]` sections for everything to work right on my TV.  It is only 48 sections, so not ridiculous or uncommon for anyone who needs to manually define a unique video mode for each arcade core.

This performance problem prevents me from controlling my character for a few seconds at the beginning of any level that starts with a resolution change, which is very bad for gameplay.  It also prevents the AmigaOS desktop or MS-DOS from accepting any keyboard/mouse input for a few seconds after a resolution change, which is not how original hardware behaves.

Most users will never use serial debugging.  Most users in Discord use SSH or other methods if they need to observe or capture output of the `MiSTer` process.  Only highly technical users will ever use serial debugging, and asking them to add a simple `console=ttyS0` parameter into `/media/usb/linux/u-boot.txt` is a very simple step for them.

**Comment by c0d3h4x0r** [comment]
I've found an alternate way to solve the performance problem with MiSTer console output. I'll post that in a separate PR.

Now all this does is enable make_linux_nice.sh to hook itself into user-startup.sh so it will be reapplied automatically even after Linux OS updates.

**Pull request closed without merging**
