### PR TITLE
Delete update_all_keep_linux_nice.sh

### PR DESCRIPTION
**Pull request by makigumo**
This script is calling an unknown script that is not in this repository.

### CODE REVIEW

**Comment by c0d3h4x0r** [comment]
That's a silly reason to remove a very useful script.  Everyone knows what `update_all.sh` is, where to get it, and what it's used for, and it's very widely used.

**Comment by c0d3h4x0r** [comment]
A different approach to solving the same problem would be to get the maintainer of `update_all.sh` to add a user option to it to automatically launch a post-script of the user's choosing when it completes its work.  I'd be fine with that approach as an alternative, but that should be implemented before this script gets deleted.

**Comment by Kitrinx** [comment]
Update_all shouldn't be referenced by the official repo as it's not part of the project nor supported by it. Please delete this script.

**Comment by c0d3h4x0r** [comment]
Filed a feature request on the update_all script instead, so go ahead and delete.

**Comment by wwark** [comment]
is it possible someone can merge this change ?

**Comment by wwark** [comment]
thank you @sorgelig and @makigumo !

**Pull request merged**
